### ISSUE TITLE
Edges on Montage and Soykbr workflows are not correct.

### ISSUE THREAD

**Issue by cloud-np** [wfcommons/wfcommons#23]
**WfCommons Information**
- WfCommons version: 0.7, master branch
- Python Version: 3.8.10

**Describe the bug**
Some of the edges in Montage and Soykbr do not have the correct weight.

**To Reproduce**
Sum of the "input" files of a child in the montage or soykbr workflows do not result in same value as
the parent "output" files.

**Expected behavior**
The sum of the input files of the child and sum of the output files in the parent should have the same weight because they describe the same edge.

**Screenshots**
Example of creating a montage workflow. (Similar to the one I am using in my program)
![image](https://user-images.githubusercontent.com/43072245/133886621-2c0cee9a-daa8-40a2-b605-0f2281a30f0d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 using wsl with Ubuntu 20.04
 - Version [e.g. 20.04]

**Additional context**
Found this problem when trying to construct the critical path of the workflow.

**Comment by rafaelfsilva** [comment]
Hello @cloud-np,

Thank you for reporting this potential issue. We have investigated the scenarios you described and we believe it is related to the following cases:

- Some of the workflow tasks may have additional input data that does not necessarily comes from the parent task (e.g., `input_file_for_t3` for task `t3` in the image below). In this case, the sum of input files sizes for task `t3` will be larger than the sum of output files sizes for task `t1`.
- In other cases, workflow tasks may have generated output data that are not necessarily used by a child task (e.g., `output_file_for_t2` for task `t2` in the image below). In this case, the sum of output files sizes for task `t2` will be larger than the sum of input files sizes for task `t4`.

<img src="https://user-images.githubusercontent.com/4711875/134267660-c087838d-6021-46b9-b279-ebc49a82a4cd.png" width="400"/>

Could you please confirm this is the behavior you have observed?

**Comment by cloud-np** [comment]
Makes sense, thanks for the example as well made it really clear!
But still, I am not so sure because I try to add up the files that come from each specific parent at the time only. 
For example T[1] parent --> T[2] child
T[1] sends 2390 to T[2]
T[2] receives 2709 from T[1] 

![image](https://user-images.githubusercontent.com/43072245/134361314-0bcb37b4-b6df-4fe9-870a-c0410a2803b9.png)

In the code above I try add the input files that exist in the child with the output files (with the same name ofc) from the parent.
Not sure if I am missing something.

**Comment by rafaelfsilva** [comment]
@cloud-np, I have investigated it further and could not reproduce your error. 

In this example code ([issue_23.py.zip](https://github.com/wfcommons/wfcommons/files/7214449/issue_23.py.zip)), it generates 100 workflows (you can choose between Montage or SoyKB) and test whether the files sizes (from one task output to another task input) match. In case the match fails, the program stops with exit code 1. I ran this program several times and no mismatch was found.

Could you please send me a JSON file from one of the workflows you generated and is causing the issue?
You can write the JSON file using the `write_json()` method from the workflow object.

**Comment by rafaelfsilva** [comment]
Hi @cloud-np, do you have any update on this issue? Thank you!

**Comment by rafaelfsilva** [comment]
I will be closing this issue as the error could not be reproduced. Please, re-open it if you experience the same issues again.
