### ISSUE TITLE
Montage workflow : no transfer file between  mImgtbl and mAdd job

### ISSUE THREAD

**Issue by arabnejad** [wfcommons/WfCommons#7]
Hi @rafaelfsilva

 I am not sure if there is a bug in workhub or not
when I generate a Montage DAG
based on the presented structure here : [https://pegasus.isi.edu/workflow_gallery/gallery/montage/index.php](https://pegasus.isi.edu/workflow_gallery/gallery/montage/index.php
)
there should be a link between `mImgtbl` and `mAdd` job
I can see in the generated JSON file,  `mAdd` is listed as a child of `mImgtbl`
however, the `mImgtbl` output link  is not appear as input file for `mAdd`
```yaml
...
 {
    "name": "mImgtbl_00000131",
    ...
    "children": [
        "mAdd_00000132"
    ],
    "files": [
        ...
        {
            "link": "output",
            "name": "509e9372-a8f4-4be5-bef5-6cfc5dcc34f9.tbl",
            "size": 2594
        }
    ]
}
...
```
i.e, there is no `509e9372-a8f4-4be5-bef5-6cfc5dcc34f9.tbl` as an input file for `mAdd_00000132` job

**Comment by rafaelfsilva** [comment]
Hi @arabnejad, thank you for reporting this issue. The following commit 723fb3c should fix the problem. Let me know if it works for you so we can close the issue.
